#bash
#$ export AWS_ACCESS_KEY_ID='YOUR_AWS_API_KEY'
#$ export AWS_SECRET_ACCESS_KEY='YOUR_AWS_API_SECRET_KEY'

- hosts: localhost
  connection: local
  gather_facts: False
  become: yes
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        update_cache: yes
        state: latest

    - name: Install mysql
      apt:
        name: mysql-server
        state: latest

    - name: Install php7
      apt:
        name: php7
        state: latest
